// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation
import ArkanaKeysInterfaces

public enum ArkanaKeys {
    @inline(__always)
    fileprivate static let salt: [UInt8] = [
        0x56, 0x46, 0x8c, 0xdd, 0x95, 0xde, 0x1b, 0x29, 0xd0, 0xe7, 0x45, 0xb9, 0x77, 0x96, 0xf9, 0x60, 0x52, 0x68, 0xc8, 0xb5, 0xe5, 0xac, 0x91, 0x9a, 0x68, 0xc6, 0x7d, 0xbb, 0x99, 0xe0, 0x9c, 0xf, 0x4d, 0x85, 0x3e, 0x84, 0x85, 0x8a, 0x65, 0x52, 0xc, 0x56, 0xea, 0xbd, 0x45, 0x43, 0x72, 0x59, 0x69, 0x60, 0x93, 0xae, 0x8e, 0x15, 0xea, 0x60, 0xb3, 0x5a, 0x70, 0x5a, 0xfb, 0x8f, 0x52, 0xd5
    ]

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> String {
        return String(decoding: encoded.enumerated().map { offset, element in
            element ^ cipher[offset % cipher.count]
        }, as: UTF8.self)
    }

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> Bool {
        let stringValue: String = Self.decode(encoded: encoded, cipher: cipher)
        return Bool(stringValue)!
    }

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> Int {
        let stringValue: String = Self.decode(encoded: encoded, cipher: cipher)
        return Int(stringValue)!
    }
}

public extension ArkanaKeys {
    struct Global: ArkanaKeysGlobalProtocol {
        public init() {}
    }
}

public extension ArkanaKeys {
    struct Staging: ArkanaKeysEnvironmentProtocol {
        public init() {}
    }
}

public extension ArkanaKeys {
    struct Release: ArkanaKeysEnvironmentProtocol {
        public init() {}
    }
}
